### ISSUE TITLE
Real time game clock?

### ISSUE THREAD

**Issue by thabrofessor** [iGBAEmu/EclipseIssues#206] opened 2020-10-26 17:32 UTC
I’ve been playing a number of roms on my IPhone that have time based events. I know some emulators are able to use the device time to run the in game clock. Is there any way in the settings to allow this, or is it coming in the 3.0 version?

**Comment by magnetardev** [comment] 2020-11-03 17:31
Duplicate of #98. It will be a part of v3 (no eta yet).

**Closed by magnetardev** 2020-11-03 17:31 UTC
