### ISSUE TITLE
Button layout doesn’t work

### ISSUE THREAD

**Issue by hazelfazel24** [iGBAEmu/EclipseIssues#52] opened 2019-11-05 23:23 UTC
# Button layout doesn’t work
*The Button layout for IOS 13 doesn’t work*
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | true | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.6 | 
## IPhone X 
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | false | 
| Languages | en-US | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Shugabuga** [comment] 2019-11-08 21:53
Duplicate of #50

**Closed by Shugabuga** 2019-11-08 21:53 UTC
