### ISSUE TITLE
Menu button stops working after a few seconds in game. 

### ISSUE THREAD

**Issue by DunDunTheMunMun** [iGBAEmu/EclipseIssues#44] opened 2019-09-19 13:03 UTC
# Description

After a few seconds in game the menu button stops working. The game is still playable and all other buttons work, however i cannot press the menu button, therefore it is impossible to save or exit the game to switch to another rom. 

# How to Reproduce

-Load Eclipse. 
-Start the rom
-press play and leave the main menu of the game.
-Try to press the menu button on eclipse.

# Device Information

iPad Pro 10.5 inch
Eclipse added to home screen 
Pokémon emerald for Gameboy Advance is rom being used.

**Comment by Shugabuga** [comment] 2020-04-21 17:37
Duplicate of #41.

**Closed by Shugabuga** 2020-04-21 17:37 UTC
Labels: Bug, Controller
