### ISSUE TITLE
Add support for audio on iOS

### ISSUE THREAD

**Issue by HuyenSofiaTUB** [iGBAEmu/EclipseIssues#71] opened 2020-01-18 09:30 UTC
# Description
Has there been a fix for the playing audio in safari on iOS issue?
There already exists a web-based emulator that has working audio on iOS devices:
https://gameplaycolor.com/ 
It asks you to enable audio every time you open the app so it’s not entirely auto-play and it’s only for gba and gbc games.
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | true | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-GB | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Shugabuga** [comment] 2020-04-21 17:34
Duplicate of #36.

**Closed by Shugabuga** 2020-04-21 17:34 UTC
