### ISSUE TITLE
GAME DATA DOWNLOADS NOT WORKING

### ISSUE THREAD

**Issue by Ausery** [iGBAEmu/EclipseIssues#133] opened 2020-07-02 00:15 UTC
# Description
The download and save feature for game data doesn't work, whenever I press download it says:
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
(Please describe your issue or feature request, in detail, here.)

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by Shugabuga** [comment] 2020-07-04 22:02
Duplicate of #54. We're aware of this and will have a fix in 3.0.

**Comment by Shugabuga** [comment] 2020-07-04 22:03
I was a bit too hasty tagging this. This is a known bug but it's related to how Eclipse handles Google Drive games.

**Comment by Shugabuga** [comment] 2020-07-28 02:53
1. That option is to download the ROM. Please download the ROM with the Google Drive app.
2. Battery save exporting will be fixed in v2.2.

**Closed** 2020-10-04 04:48 UTC
Labels: Bug, v2.2
