### ISSUE TITLE
Voice not working

### ISSUE THREAD

**Issue by Absepsem** [iGBAEmu/EclipseIssues#69] opened 2020-01-09 23:31 UTC
# Description. No audio
*Please describe your issue here.* says the safari don’t allow auto play back or something like that
# Device Information. iOS 13.3
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | false | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | true | 
| Games Setup | true | 
| Repos Setup | true | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | false | 
| Languages | en-US | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Shugabuga** [comment] 2020-04-21 17:32
Duplicate of #36.

**Closed by Shugabuga** 2020-04-21 17:32 UTC
