### ISSUE TITLE
I am on iOS 13.3 iPhone 11 pro and can load games but the buttons don’t work.

### ISSUE THREAD

**Issue by timbothegamer** [iGBAEmu/EclipseIssues#63] opened 2019-12-23 21:18 UTC
# Description
*Please describe your issue here.*
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | false | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.6 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | false | 
| Languages | en-US | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Mohawks55** [comment] 2019-12-27 12:06
Have had the same issue. Hopefully it gets fixed soon

**Comment by hatori-hanzo** [comment] 2019-12-27 14:45
Same issue. 

Iphone11 iOS 13.3 

buttons not working on Pokémon emerald  

Halp

**Comment by hatori-hanzo** [comment] 2020-01-03 10:24
Eclipseemu - buttons seem to be resolved for me, although now most recent update now had landscape display sizing issues

**Comment by Shugabuga** [comment] 2020-04-21 17:43
Duplicate of #45.

**Closed by Shugabuga** 2020-04-21 17:43 UTC
Labels: Bug, Controller
