### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by naturiagod** [iGBAEmu/EclipseIssues#113] opened 2020-05-28 05:12 UTC
Please help bring sound for iPhone XS please.

**Comment by Cisc0-gif** [comment] 2020-06-02 22:23
yeah im having the same issue. iPhone 8, IOS 13.2, running on chrome and safari.

**Comment by Shugabuga** [comment] 2020-06-12 02:59
We're working on it. Duplicate of #36.

**Closed by Shugabuga** 2020-06-12 02:59 UTC
