### ISSUE TITLE
Google drive login

### ISSUE THREAD

**Issue by jeffmcjeff312** [iGBAEmu/EclipseIssues#128] opened 2020-06-28 11:40 UTC
# Description

Any time I leave the app or go back my google drive gets logged out and all progress is gone

# How to Reproduce

By leaving the app and going back

# Device Information

iPad, safari

**Comment by cliffhanger1** [comment] 2020-07-02 21:31
same here

**Comment by Shugabuga** [comment] 2020-07-04 21:59
Duplicate of #105. Please direct all discussion there.

**Closed by Shugabuga** 2020-07-04 21:59 UTC
Labels: Duplicate
