### ISSUE TITLE
Buttons don’t work

### ISSUE THREAD

**Issue by colnate** [iGBAEmu/EclipseIssues#89] opened 2020-04-09 17:31 UTC
Buttons
Some of my buttons don’t work.
I have a iPhone XR with the newest software update 
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | nl-NL | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Shugabuga** [comment] 2020-04-21 17:57
Update iOS to iOS 13.2. iOS 13.1.3 is *not* the latest version and apparently fixes controls (regardless, we're still looking into the issue).

Duplicate of #45.

**Closed by Shugabuga** 2020-04-21 17:57 UTC
