### ISSUE TITLE
Sound issue.

### ISSUE THREAD

**Issue by FinesseLP** [iGBAEmu/EclipseIssues#119] opened 2020-06-10 00:59 UTC
Sound does not work on safari for any game I’ve played so far.

While I’m aware that this has been an issue for a while, I’m also aware of the limiting game experience this leaves users with.
Please can we fix this?

**Comment by Shugabuga** [comment] 2020-06-12 02:58
We're working on it. Duplicate of #36.

**Closed by Shugabuga** 2020-06-12 02:58 UTC
