### ISSUE TITLE
The menu button doesn’t work

### ISSUE THREAD

**Issue by luisp191101** [iGBAEmu/EclipseIssues#111] opened 2020-05-21 17:40 UTC
# Description

(Please describe your issue or feature request, in detail, here.)

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by N-Games** [comment] 2020-05-21 17:42
This is a repoduce of: https://github.com/iGBAEmu/EclipseIssues/issues/41.

**Comment by magnetardev** [comment] 2020-05-21 19:42
Duplicate of #41

**Closed by magnetardev** 2020-05-21 19:42 UTC
