### ISSUE TITLE
I am on iPad mini 4 ios 13... the game loads the A and B buttons do not work

### ISSUE THREAD

**Issue by shreyasclutch** [iGBAEmu/EclipseIssues#68] opened 2020-01-01 02:54 UTC
# Description

(Please describe your issue or feature request, in detail, here.)

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by Shugabuga** [comment] 2020-04-21 17:44
Is it only the A and B buttons that are unresponsive?

If so, see #45.

**Comment by magnetardev** [comment] 2020-04-24 03:12
Would you mind testing this out and seeing if it works? This is what we’ll be using in v3, so if it works then that’ll be one common issue off our list. Thanks.

https://zenithdevs.github.io/ControllerKit/demo/

**Comment by magnetardev** [comment] 2020-11-03 18:34
Duplicate of #45

**Closed by magnetardev** 2020-11-03 18:34 UTC
Labels: Bug, Controller
