### ISSUE TITLE
Game won’t save

### ISSUE THREAD

**Issue by Bluedudepro** [iGBAEmu/EclipseIssues#83] opened 2020-03-15 11:44 UTC
I was playing a game and it didn’t save when I pressed the save button, so I thought it might have been something wrong with what I had downloaded so I tried other games but none of my them would save so then I checked to see if it was something with my iPhone but it didn’t save on my iPad either. Please fix this because it’s really annoying to have to start a game from the start every time.

**Comment by arrofacttt** [comment] 2020-04-02 23:29
Yea

**Comment by Shugabuga** [comment] 2020-04-21 17:55
Are you using the in-game save feature too?

Duplicate of #60.

**Closed by Shugabuga** 2020-04-21 17:55 UTC

**Comment by xXIDarkIXx** [comment] 2020-07-27 21:55
This did not work
