### ISSUE TITLE
Game stuck

### ISSUE THREAD

**Issue by hunter931** [iGBAEmu/EclipseIssues#123] opened 2020-06-22 04:41 UTC
# Description
When loaded on to the game the game does not progress and is stuck on the first 
![D867AE78-2E51-47AB-A9DD-919577811723](https://user-images.githubusercontent.com/67253538/85249232-1967c780-b44b-11ea-964a-9ec934bbc5c0.png)
caption
# Device Information
iPhone 6s 13.0
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhone | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-GB | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by magnetardev** [comment] 2020-11-03 18:32
This is a controller related bug, so technically a duplicate of #45

**Closed by magnetardev** 2020-11-03 18:32 UTC
