### ISSUE TITLE
Sound is not working

### ISSUE THREAD

**Issue by Consumedgrub2** [iGBAEmu/EclipseIssues#72] opened 2020-01-21 06:55 UTC
# Description 
*Please describe your issue here.* - sound is not working.
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| never | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhone | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 12_4_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-US | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Shugabuga** [comment] 2020-04-21 17:31
Duplicate of #36.

**Closed by Shugabuga** 2020-04-21 17:31 UTC
