### ISSUE TITLE
Menu button does not work

### ISSUE THREAD

**Issue by collinrosee** [iGBAEmu/EclipseIssues#42] opened 2019-09-12 14:59 UTC
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | true | 
| Skins Setup | true | 
| Eclipse Version | 2.1.3 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhone | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-US | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Csgm** [comment] 2019-09-15 18:26
I’m having this issue

**Comment by littlehackboi** [comment] 2019-12-18 20:14
Please I need a solution

**Comment by Shugabuga** [comment] 2020-04-21 17:37
Duplicate of #41.

**Closed by Shugabuga** 2020-04-21 17:37 UTC
Labels: Bug, Controller
