### ISSUE TITLE
Some Buttons dont work

### ISSUE THREAD

**Issue by jayNPC** [iGBAEmu/EclipseIssues#50] opened 2019-10-10 00:38 UTC
> # Description

*Please describe your issue here.*
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | true | 
| Skins Setup | true | 
| Eclipse Version | 2.1.6 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhone | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-US | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Shugabuga** [comment] 2019-11-08 21:53
Duplicate.

**Comment by Shugabuga** [comment] 2020-04-21 17:43
Duplicate of #45.

**Closed by Shugabuga** 2020-04-21 17:43 UTC
Labels: Bug, Controller
