### ISSUE TITLE
Real time clock link in system settings on emulator 

### ISSUE THREAD

**Issue by dantheman124** [iGBAEmu/EclipseIssues#260] opened 2021-01-25 02:54 UTC
# Description

(Many gba games and roms have issues with real time clocks making this emulator useless for game profession)

# How to Reproduce

(.)

# Device Information
 (Running the most recent web app on io14.3 which is great to bypass the known issues with rom playing on apple device, however all Roms use real time clock which stops gameplay in almost all games that I am trying to play, I suggest updating the system settings to add a clock date and time which can be adjusted for the gba rom games to pick up a time and bypass this issue. )

**Comment by magnetardev** [comment] 2021-04-16 14:49
Duplicate of #98

**Closed** 2021-04-16 14:49 UTC
