### ISSUE TITLE
Cheat code support (such as Action Replay and GameShark)

### ISSUE THREAD

**Issue by skullkrusher567** [iGBAEmu/EclipseIssues#74] opened 2020-02-07 23:05 UTC
Just as the title states I would like to request a feature to input cheat codes . 

love playing gen 3 Pokémon games and which is why I got eclipse for , but sometimes when you gotta grind to be able to beat the next gym leader or elite 4 it takes awhile . That's why I love the infinite rare candy cheat so if you guys could allow us to input cheats that that would be awesome.

**Comment by moonslayer57** [comment] 2020-05-19 18:51
The one thing missing from the emulator is cheat support

**Comment by Shugabuga** [comment] 2020-05-20 17:27
Duplicate of #74.

**Closed** 2020-05-20 17:27 UTC
Labels: Enhancement

**Comment by chadillac13** [comment] 2021-03-09 14:14
Are they ever going to make a cheat option??

**Comment by jamesmathews7** [comment] 2021-06-03 20:31
We need cheat options please I’m begging u
