### ISSUE TITLE
No game audio

### ISSUE THREAD

**Issue by Jenna3715** [iGBAEmu/EclipseIssues#39] opened 2019-07-13 11:34 UTC
# Description
I tried both Somari, and Link's Awakening DX, but neither of them emitted any sound whatsoever. I even tried resetting all Eclipse settings, the "Request Desktop Site" button in Safari, enabling experimental Safari features, disabling content blockers and privacy settings, and even different methods of adding the games, but still to no avail. 

# Device Information
## States
Audio Enabled: true 
Auto-Save Enabled: true 
Current Skin Set?: true 
Desktop Mode Enabled: false 
Full Screen Enabled: false 
Game List Initialized?: true 
Repo List Initialized?: true 
Skin List Initialized?: true 
Set-Up Successful?: 2.0.8 
## Device
Device (F7): Desktop  
User Agent: Mozilla/5.0 (Macintosh- Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15 
Do Not Track: Not Set 
Cookies Enabled?: true 
ServiceWorker Support: false 
Languages: en-US 
Vendor: Apple Computer, Inc. 
Platform: iPhone

**Comment by Shugabuga** [comment] 2020-04-21 17:32
Duplicate of #36.

**Closed by Shugabuga** 2020-04-21 17:32 UTC
Labels: Audio
