### ISSUE TITLE
Buttons don’t work

### ISSUE THREAD

**Issue by UserNamesAreOutdated** [iGBAEmu/EclipseIssues#86] opened 2020-04-07 23:35 UTC
Only Start, menu, L and R work on Eclipse emulator, A and B don’t work and this makes playing any Rom difficult 

Thanks for reading (:

**Comment by dandi24403** [comment] 2020-04-10 13:14
A,B and cross buttons doesn’t work what can i do?

**Comment by Shugabuga** [comment] 2020-04-21 17:46
Duplicate of #45.

**Closed by Shugabuga** 2020-04-21 17:46 UTC
