### ISSUE TITLE
Save Issue Button Broken

### ISSUE THREAD

**Issue by MegamiSaikou** [iGBAEmu/EclipseIssues#82] opened 2020-03-11 02:27 UTC
# Description
Eclipse allows me to save, but then when I press the save button nothing happens. I have to restart from the beginning and I can't get it back.
# How to Reproduce
When you upload a ROM, start playing like you usually do. But when you start trying to save from the menu button nothing happens. When you upload the ROM again, the data is gone.
# Device Information
Google Chrome
Chromebook
v2.1.10
ROM Final Fantasy Advance Tactics

**Comment by Shugabuga** [comment] 2020-04-21 17:54
Are you using the in-game save feature too?

Possible duplicate of #60.

**Closed by Shugabuga** 2020-04-21 17:54 UTC
