### ISSUE TITLE
Menú button not working

### ISSUE THREAD

**Issue by whiteseal6** [iGBAEmu/EclipseIssues#94] opened 2020-04-16 05:20 UTC
I am new to the app maybe I am just not doing something right. This is my first time using it and I had followed a video telling me what to do and when I did it everything was working fin. I loaded the rom and the game was starting up and everything was working fine, except for when I tried clicking the menu button; it wouldn’t let me. The start and select button worked fine but the menu button wouldn’t work. The games I was playing was Pokémon emerald, Pokémon leaf green, and Pokémon silver.

**Comment by Shugabuga** [comment] 2020-04-21 17:35
Duplicate of #41.

**Closed by Shugabuga** 2020-04-21 17:35 UTC
