### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by Masoud159** [iGBAEmu/EclipseIssues#97] opened 2020-04-18 23:27 UTC
# Description
*Please describe your issue here.*there is no volume on the games can you fix that issue please 
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | true | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhone | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Masoud159** [comment] 2020-04-18 23:28
No volume on games

**Comment by Shugabuga** [comment] 2020-04-21 17:31
Duplicate of #36.

**Closed by Shugabuga** 2020-04-21 17:31 UTC
