### ISSUE TITLE
Tge menu button doesn’t work, which makes saving the game impossible, because you have to menu save it and ingame save it

### ISSUE THREAD

**Issue by swagdec77** [iGBAEmu/EclipseIssues#48] opened 2019-10-01 11:45 UTC
# Description

(Please describe your issue or feature request, in detail, here.)

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by Shugabuga** [comment] 2020-04-21 17:38
Eclipse should auto-save every minute or so, which may be a useful stop-gap until we can pinpoint this and other similar bugs.

Duplicate of #41.

**Closed by Shugabuga** 2020-04-21 17:38 UTC
Labels: Bug, Controller
