### ISSUE TITLE
When will the audio be fixed?

### ISSUE THREAD

**Issue by maikolokko** [iGBAEmu/EclipseIssues#95] opened 2020-04-16 11:09 UTC
# Description
*Please describe your issue here.*
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | false | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | nl-NL | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by Shugabuga** [comment] 2020-04-21 17:30
Duplicate of #36.

**Closed by Shugabuga** 2020-04-21 17:30 UTC
