### ISSUE TITLE
Fast forward slows down game to half speed

### ISSUE THREAD

**Issue by Javaboy01** [iGBAEmu/EclipseIssues#208] opened 2020-11-01 09:23 UTC
# While using the emulator I happen to use the fast forward option quite a lot as some games I download take a little long but it ended up slowing down my game. Now whenever I open up a GBA game it’s always slowed down to half speed.

Was slowing down games after a couple uses

#204 To reproduce you would need to use the fast forward feature back and forth from normal to fast.

I don’t have a direct guide on how to replicate it but I’m assuming it’s very easy due me using the application for only two days. Basically what I said above but constantly changing back and forth for two days and on that I can take fault, I’m just so used to other emulators where I can do that consistently.

# iPhone 11 XR

**Comment by magnetardev** [comment] 2020-11-03 17:27
Duplicate of #204

**Closed by magnetardev** 2020-11-03 17:27 UTC
