### ISSUE TITLE
Mobile button issues

### ISSUE THREAD

**Issue by EnderDreamer15** [iGBAEmu/EclipseIssues#47] opened 2019-09-27 13:28 UTC
# Description

(Please describe your issue or feature request, in detail, here.)

**Buttons dont work in game except start, select and menu buttons** 

# How to Reproduce

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

**Load any game in ios 13 on the safari or app version of eclipse and try to play**

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Device: ios ipad 6th generation 
Version: ios 13
Eclipse version: 2.1.6**

**Comment by swagdec77** [comment] 2019-10-01 11:47
Strange, my menu button is the one that doesn’t work

**Comment by Shugabuga** [comment] 2020-04-21 17:39
Duplicate of #45.

**Closed by Shugabuga** 2020-04-21 17:39 UTC
Labels: Bug, Controller
