### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by Andooty** [iGBAEmu/EclipseIssues#124] opened 2020-06-22 06:36 UTC
# Description
*Please describe your issue here.*
I’m unable to save And load my Pokémon game
# Device Information
iPhone 6s
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | true | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhone | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-GB | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by magnetardev** [comment] 2020-11-03 18:44
Duplicate of #60

**Closed by magnetardev** 2020-11-03 18:44 UTC
