### ISSUE TITLE
Games 

### ISSUE THREAD

**Issue by sixplayed** [iGBAEmu/EclipseIssues#295] opened 2021-03-26 16:58 UTC
Games that don’t work.
Hi, I want to report that there’s a game that I really want to play but it doesn’t let me that is dragon ball Buu fury’s. When I enter the screen turns into a white screen and there’s nothing.
iPhone X 64gb
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 30000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.2.0 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | es-es | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by magnetardev** [comment] 2021-04-16 14:48
Duplicate of #201

**Closed** 2021-04-16 14:48 UTC
