### ISSUE TITLE
Ipad buttons dont work

### ISSUE THREAD

**Issue by Zealous02** [iGBAEmu/EclipseIssues#79] opened 2020-03-02 04:00 UTC
# Description all movements and a and b dont work
*Please describe your issue here.*
# Device Information  ipad pro 6th gen ios 1.13.3
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | true | 
| Skins Setup | true | 
| Eclipse Version | 2.1.10 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPad | 
| User Agent | Mozilla/5.0 (Macintosh- Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | en-US | 
| Vendor | Apple Computer, Inc. | 
 | Platform | MacIntel |

**Comment by Shugabuga** [comment] 2020-04-21 17:45
Duplicate of #45.

**Closed by Shugabuga** 2020-04-21 17:45 UTC
