### ISSUE TITLE
Bluetooth controller playability 

### ISSUE THREAD

**Issue by richie22456** [iGBAEmu/EclipseIssues#93] opened 2020-04-14 01:23 UTC
# Description 
I was just wondering if you could add a feature that would let you use a Bluetooth controller to play the games on the application 

# How to Reproduce

# Device Information

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by Shugabuga** [comment] 2020-04-21 17:47
Duplicate of #92.

**Closed by Shugabuga** 2020-04-21 17:47 UTC
