### ISSUE TITLE
Button problems

### ISSUE THREAD

**Issue by jacobclarson** [iGBAEmu/EclipseIssues#40] opened 2019-08-30 18:49 UTC
# Description
*The buttons, especially the A and B buttons will not input consistently and they will stick or continuously input when pressed once. This happens on most games and is especially worse on some games. *
# Device Information
## States
Audio Enabled: true 
Auto-Save Enabled: true 
Current Skin Set?: true 
Desktop Mode Enabled: false 
Full Screen Enabled: false 
Game List Initialized?: true 
Repo List Initialized?: true 
Skin List Initialized?: true 
Set-Up Successful?: 2.0.8 
## Device
Device (F7): iOS iPhone  
User Agent: Mozilla/5.0 (iPhone- CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1 
Do Not Track: Not Set 
Cookies Enabled?: true 
ServiceWorker Support: false 
Languages: en-US 
Vendor: Apple Computer, Inc. 
Platform: iPhone

**Comment by Shugabuga** [comment] 2019-08-30 19:28
Duplicate of #29

**Closed by Shugabuga** 2019-08-30 19:28 UTC
