### ISSUE TITLE
Volume for iPhone XS. 

### ISSUE THREAD

**Issue by naturiagod** [iGBAEmu/EclipseIssues#120] opened 2020-06-10 06:09 UTC
This is very confusing. I can’t seem to have any volume. You guys since last year ve had this issue. Any way you can fix it? Be more active on this a lot of people appreciate the work you do. This is 2020 and with the quartine, it will be awesome If you fix this.

**Comment by Shugabuga** [comment] 2020-06-12 02:58
We're working on it. Duplicate of #36.

**Closed by Shugabuga** 2020-06-12 02:58 UTC
