### ISSUE TITLE
Saving

### ISSUE THREAD

**Issue by cmalenich** [iGBAEmu/EclipseIssues#109] opened 2020-05-21 01:52 UTC
The games saves are all linked when the game saves the save file is not foe that game but all the other ones for example i have pokemon outlaw and pokemon orange islands rom and when i save in one game ir transfers to the next which is a completely different game and has a completely different file like those two games are individual games but i save in one and thw save is on a completely different game ita happening with all my roms it needs fixed because the games are each individual games and should have completely different save files instead of just one through all the games 

(Please describe your issue or feature request, in detail, here.)

Save in pokemon outlaw for example and save in pokemon orange islands and it would ve the same save files but two completely different games that share the same save file

(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

Iphone 11 pro max 

(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by Vendrick9** [comment] 2020-06-27 07:35
I have the same problem!! And I want that fix because they are different games but using the same game as base but also is totally different both!

**Comment by magnetardev** [comment] 2020-11-03 17:57
Duplicate of #73.

**Closed by magnetardev** 2020-11-03 17:57 UTC
