### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by mrnijssen3** [iGBAEmu/EclipseIssues#184] opened 2020-09-15 23:42 UTC
I don’t have any volume anymore 
# Device Information
## States
| State | Value | 
|-------|-------| 
| Audio Enabled | true | 
| Auto-Save Rate| 60000 | 
| Current Skin Set | true | 
| Desktop Mode Enabled | false | 
| Full Screen Enabled | false | 
| Games Setup | true | 
| Repos Setup | false | 
| Skins Setup | true | 
| Eclipse Version | 2.2.0 | 
## Device
| State | Value | 
|-------|-------| 
| Device (F7) | iOSiPhoneiPhone X | 
| User Agent | Mozilla/5.0 (iPhone- CPU iPhone OS 13_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Mobile/15E148 Safari/604.1 | 
| Do Not Track | Not Set | 
| Cookies Enabled | true | 
| ServiceWorker Support | true | 
| Languages | nl | 
| Vendor | Apple Computer, Inc. | 
 | Platform | iPhone |

**Comment by magnetardev** [comment] 2020-11-03 18:37
Duplicate of #179

**Closed by magnetardev** 2020-11-03 18:37 UTC
Labels: Cannot Replicate
