### ISSUE TITLE
Real time clock.

### ISSUE THREAD

**Issue by FinesseLP** [iGBAEmu/EclipseIssues#118] opened 2020-06-10 00:58 UTC
# a real time clock feature is desperately needed. Currently play your emulator on an iPad Pro and one reason the clock does not register for in-game prevents. This of course limits the amount of game playability.

**Comment by magnetardev** [comment] 2020-11-03 17:30
Duplicate of #98. Further discussion will be there.

**Closed by magnetardev** 2020-11-03 17:30 UTC
