### ISSUE TITLE
Real time clock

### ISSUE THREAD

**Issue by Jadeira** [iGBAEmu/EclipseIssues#225] opened 2020-11-30 21:20 UTC
# Description
Currently experiencing issue with real time clock. Finding no option to enable it. Pokémon radical red uses time based events. Stuck at 12 at night 
(Please describe your issue or feature request, in detail, here.)

# How to Reproduce
Load any game using a real time clock
(Please give a step-by-step guide on how to reproduce the issue you are having. Remove this if it's a feature request.)

# Device Information
iPhone 10
(Please put as much information on your web browser, device, and Eclipse install. If you want this pre-filled, please use
the debugger to export this data, as described on https://github.com/iGBAEmu/EclipseIssues/blob/master/README.md#debugging)

**Comment by HadronSounds** [comment] 2020-12-14 17:13
Would love to see this too!

**Comment by magnetardev** [comment] 2021-04-16 14:49
Duplicate of #98

**Closed by magnetardev** 2021-04-16 14:50 UTC
